name: Create Jira Issue

on:
  push:
    branches:
      - main

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Jira Issue
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: "YOUR_PROJECT_KEY"
        run: |
          curl -X POST -u $JIRA_EMAIL:$JIRA_API_TOKEN -H "Content-Type: application/json" \
          --data '{
              "fields": {
                  "project": {
                      "key": "'"$JIRA_PROJECT_KEY"'"
                  },
                  "summary": "Issue created from GitHub",
                  "description": "This issue was created automatically from a GitHub Action",
                  "issuetype": {
                      "name": "Task"
                  }
              }
          }' $JIRA_URL/rest/api/3/issue
